/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Opaque JS handle around the Rust context. JS consumers pass this
 * to [`handle_json_rpc_body`] repeatedly; internally we keep the
 * cNFT store, cache, upstream, and decoders alive for the lifetime
 * of the JS object.
 */
export declare class HeliusContext {
  /**
   * Create a new context. All options are optional — defaults
   * target a local Surfpool install.
   */
  constructor(options?: HeliusContextOptions | undefined | null)
}

/**
 * Dispatch one JSON-RPC request body against the given context.
 *
 * - Returns `Some(responseJson)` when the method is one the service
 *   layer handles natively.
 * - Returns `None` when the method is unknown / the body is malformed
 *   — the caller is expected to defer to its own passthrough (MSW's
 *   `passthrough()`, Nock's `.allowUnmocked()`, undici's net-connect).
 *
 * Body may be a JSON string or a pre-parsed object serialized by the
 * caller. Response is a JSON-encoded string so it drops straight into
 * most mock-HTTP APIs (e.g. `HttpResponse.json(JSON.parse(r))`).
 */
export declare function handleJsonRpcBody(ctx: HeliusContext, body: string): Promise<string | null>

/**
 * Options accepted by [`create_helius_context`]. All fields optional
 * with sensible defaults for the happy path (local Surfpool).
 */
export interface HeliusContextOptions {
  /** Upstream Solana RPC URL. Default: `http://127.0.0.1:8899`. */
  upstreamUrl?: string
  /** Upstream RPC timeout in milliseconds. Default: `10_000`. */
  rpcTimeoutMs?: number
}

/** Crate version — handy for sanity checks in JS tests. */
export declare function version(): string
