// Generate the MPL Core client from a pinned Anchor/Shank IDL.
//
// This script reads `idls/mpl_core.json` (pinned to a specific commit on
// metaplex-foundation/mpl-core — see idls/mpl_core.source.json) and emits
// a Solana Kit-compatible TypeScript client into src/generated/mpl-core.
//
// Run via:   make codegen
// Refresh:   make update-idl   (fetches latest main, rewrites idls/, reruns this)
//
// The generated output is committed to the repo so installs are
// reproducible without running codegen. `src/generated/` is the only
// place in src/ where you'll see auto-generated files — everything else
// is hand-maintained.
//
// Note: Codama's default output is a mini-package layout
// (<out>/package.json + <out>/src/generated/). We flatten it so our
// import paths stay shallow: src/generated/mpl-core/accounts/assetV1.ts
// instead of src/generated/mpl-core/src/generated/accounts/assetV1.ts.
// Relative imports within the generated code survive the move.

import { createFromRoot } from "codama";
import { rootNodeFromAnchor, type AnchorIdl } from "@codama/nodes-from-anchor";
import { renderVisitor } from "@codama/renderers-js";
import {
  readFileSync,
  rmSync,
  existsSync,
  mkdtempSync,
  cpSync,
  mkdirSync,
  writeFileSync,
  readdirSync,
  statSync,
} from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { tmpdir } from "node:os";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

const idlPath = resolve(repoRoot, "idls", "mpl_core.json");
const finalOutputPath = resolve(repoRoot, "src", "generated", "mpl-core");

const idlRaw = readFileSync(idlPath, "utf-8");
const idl = JSON.parse(idlRaw) as AnchorIdl;

console.log(`[codama] IDL:    ${idlPath}`);
console.log(`[codama] Output: ${finalOutputPath}`);

// Render into a temporary directory first, then move just the useful
// subtree (src/generated/) into our target path. This gives us a flat
// layout without having to post-process Codama's output in place.
const scratch = mkdtempSync(resolve(tmpdir(), "surfpool-helius-codama-"));
try {
  const codama = createFromRoot(rootNodeFromAnchor(idl));
  await codama.accept(renderVisitor(scratch));

  const scratchInner = resolve(scratch, "src", "generated");
  if (!existsSync(scratchInner)) {
    throw new Error(
      `Expected generated output at ${scratchInner} — Codama layout changed?`,
    );
  }

  if (existsSync(finalOutputPath)) {
    rmSync(finalOutputPath, { recursive: true, force: true });
  }
  mkdirSync(finalOutputPath, { recursive: true });
  cpSync(scratchInner, finalOutputPath, { recursive: true });
} finally {
  rmSync(scratch, { recursive: true, force: true });
}

// Prune subtrees we don't use. The proxy only reads account data, so
// instruction builders, program declarations, and error enums are dead
// code — and they pull in extra transitive deps like
// @solana/program-client-core that we'd otherwise have to install just
// to shut TypeScript up. Keeping `accounts/` and `types/` is all we need.
const pruneDirs = ["instructions", "programs", "errors"];
for (const dir of pruneDirs) {
  const path = resolve(finalOutputPath, dir);
  if (existsSync(path)) {
    rmSync(path, { recursive: true, force: true });
  }
}

// Rewrite the root index to match what we kept.
writeFileSync(
  resolve(finalOutputPath, "index.ts"),
  `// AUTOGENERATED — see scripts/codama.ts.
// Only accounts/ and types/ are rendered; instructions/, programs/, and
// errors/ are pruned by the generator because the proxy doesn't use them.

export * from "./accounts/index.js";
export * from "./types/index.js";
`,
);

// Post-process imports. Codama emits TypeScript-style bare specifiers
// ("from '../types'", "from './assetV1'") which TSC with Bundler
// resolution accepts, but Node ESM requires explicit .js extensions and
// /index.js for directory imports. We rewrite every relative import to
// its resolved runtime path so `node dist/...` actually works.
function walkTs(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const p = resolve(dir, entry);
    const s = statSync(p);
    if (s.isDirectory()) {
      out.push(...walkTs(p));
    } else if (entry.endsWith(".ts")) {
      out.push(p);
    }
  }
  return out;
}

function normalizeImport(fileDir: string, spec: string): string {
  if (!spec.startsWith(".")) return spec;
  if (spec.endsWith(".js") || spec.endsWith(".json")) return spec;
  const abs = resolve(fileDir, spec);
  if (existsSync(`${abs}.ts`)) return `${spec}.js`;
  if (existsSync(abs) && statSync(abs).isDirectory()) {
    return `${spec}/index.js`;
  }
  return spec;
}

// Matches any relative specifier: "." / ".." / "./x" / "../y" / "./a/b"
// — i.e. starts with `.` and contains no protocol or bare package prefix.
const importRegex =
  /((?:from|import)\s*)(["'])(\.[^"']*)\2/g;

let rewrittenFiles = 0;
let rewrittenImports = 0;
for (const file of walkTs(finalOutputPath)) {
  const src = readFileSync(file, "utf-8");
  const fileDir = dirname(file);
  let changedHere = 0;
  const next = src.replace(importRegex, (_m, pre, quote, spec) => {
    const normalized = normalizeImport(fileDir, spec);
    if (normalized !== spec) changedHere++;
    return `${pre}${quote}${normalized}${quote}`;
  });
  if (changedHere > 0) {
    writeFileSync(file, next);
    rewrittenFiles++;
    rewrittenImports += changedHere;
  }
}

console.log(`[codama] Generated client written to ${finalOutputPath}`);
console.log(`[codama] Pruned: ${pruneDirs.join(", ")}`);
console.log(
  `[codama] Rewrote ${rewrittenImports} imports across ${rewrittenFiles} files for Node ESM`,
);
